database:
  image: postgres:9.5
  ports:
    - "5432:5432"

redis:
  image: redis
  volumes:
    - /var/lib/docker/data/redis:/data
  ports:
    - "6379:6379"

box:
  image: busybox
  volumes:
    - /box

platform:
  build: .
  command: ./script/app.sh
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock
  volumes_from:
    - box
  labels:
      - convox.port.443.protocol=tls
      - convox.port.443.proxy=true
  ports:
      - 5000:5000
      - 80:4000
      - 443:4001
  links:
    - database
    - redis
  env_file: .env
  environment:
    - RACK_ENV
    - STRIPE_SECRET_KEY
    - STRIPE_PUBLISHABLE_KEY
    - SMTP_HOST
    - SMTP_USERNAME
    - SMTP_PASSWORD
    - SMTP_DOMAIN
    - APP_URL
    - GITHUB_TOKEN
    - STRIPE_WEBHOOK_PASSWORD
    - GITHUB_CLIENT_ID
    - GITHUB_CLIENT_SECRET
    - GITHUB_WEBHOOK_TOKEN
    - GITHUB_BOT_LOGIN
    - AES_KEY
    - HMAC_KEY
    - WARDEN_GITHUB_VERIFIER_SECRET
    - SESSION_SECRET
    - BASIC_AUTH_SECRET
