source "https://rubygems.org"

gem "rack", "1.5.4"
gem "thin"
gem "rake"
gem "sinatra"
gem "sinatra-contrib"
gem "sinatra-assetpack", "0.3.3"
gem "rack-contrib"
gem "rack-flash3"
gem "sinatra-activerecord"
gem "therubyracer"
gem "less"
gem "pg"
gem "active_model_serializers"
gem "protected_attributes"
gem "sentry-raven", "~> 0.15.2"
gem "bcrypt"
gem "warden"
gem "warden-github"
gem "docker-api"
gem "redis"
gem "sidekiq"
gem "secure_headers", "3.0.0.pre"
gem "sequential"
gem "redcarpet"
gem "stripe"
gem 'stripe-ruby-mock', '~> 2.2.1', require: 'stripe_mock'
gem "will_paginate", "~> 3.0.6"
gem "pony"

group :development, :test do
  gem "rspec"
  gem "webmock"
  gem "mock_redis"
  gem "database_cleaner"
  gem "factory_girl"
  gem "faker"
end
