module Pushbit
  autoload :BaseWorker, "app/workers/base_worker"
  autoload :EmailWorker, "app/workers/email_worker"
  autoload :DockerContainerWorker, "app/workers/docker_container_worker"
  autoload :GithubEventWorker, "app/workers/github_event_worker"
  autoload :ManualEventWorker, "app/workers/manual_event_worker"
  autoload :CronEventWorker, "app/workers/cron_event_worker"
  autoload :SetupEventWorker, "app/workers/setup_event_worker"
  autoload :TaskCompletedEventWorker, "app/workers/task_completed_event_worker"
  autoload :RepoSyncronizationWorker, "app/workers/repo_syncronization_worker"
  autoload :BehaviorSyncronizationWorker, "app/workers/behavior_syncronization_worker"
  autoload :TaskCompletedWorker, "app/workers/task_completed_worker"
  autoload :GithubIssueWorker, "app/workers/github_issue_worker"
  autoload :GithubPullRequestWorker, "app/workers/github_pull_request_worker"
  autoload :GithubLineCommentWorker, "app/workers/github_line_comment_worker"
end
