default: &default
  adapter:  postgresql
  url: <%= ENV["DATABASE_URL"]  %>
  pool: 50
  timeout: 5000

staging:
  <<: *default
  pool: 50

production:
  url: <%= ENV["DATABASE_URL"]  %>
  pool: 50

development:
  url: <%= ENV["DATABASE_URL"]  %>
  connect_retry_timeout: 1

test:
  adapter:  postgresql
  database: test 
  username: postgres 
  password: password 
  host: database 
  pool: 50
  timeout: 5000
  connect_retry_timeout: 1

ci:
  database: circle_ruby_test
  timeout: 5000
  pool: 5
  username: ubuntu
  adapter: postgresql
  host: localhost
