default: &default
  adapter:  postgresql
  url: <%= ENV["DATABASE_URL"]  %>
  pool: 50
  timeout: 5000

staging:
  <<: *default
  pool: 50

production:
  url: <%= ENV["DATABASE_URL"]  %>
  pool: 50

development:
  url: <%= ENV["DATABASE_URL"]  %>
  connect_retry_timeout: 1

test:
  adapter: sqlite3
  encoding: utf8
  pool: 5
  timeout: 5000
  database: ":memory:"
  verbosity: quiet

ci:
  database: circle_ruby_test
  timeout: 5000
  pool: 5
  username: ubuntu
  adapter: postgresql
  host: localhost
