default: &default
  adapter: postgresql
  host: database
  username: postgres
  password: password
  port: 5432
  pool: 50
  timeout: 5000

production:
  url: <%= ENV["DATABASE_URL"]  %>

development:
  <<: *default
  database: app

test:
  <<: *default
  database: pushbit-test

ci:
  database: circle_ruby_test
  timeout: 5000
  pool: 5
  username: ubuntu
  adapter: postgresql
  host: localhost
